[tool.poetry]
name = "duck-test"
version = "0.1.0"
description = ""
authors = ["Jason Sanders <me@fictitiouswizard.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
